genres = {
    "12th Century",
    "13th Century",
    "14th Century",
    "15th Century",
    "16th Century",
    "17th Century",
    "18th Century",
    "1961-1975",
    "19th Century",
    "1st Grade",
    "20th Century",
    "21st Century",
    "2nd Grade",
    "40k",
    "AUTOBIOGRAPHY",
    "Abuse",
    "Academia",
    "Academic",
    "Academics",
    "Accounting",
    "Action",
    "Activism",
    "Activities",
    "Adaptations",
    "Adhd",
    "Adolescence",
    "Adoption",
    "Adult",
    "Adult Fiction",
    "Adventure",
    "Africa",
    "African American",
    "African American Literature",
    "African American Romance",
    "African Literature",
    "Agriculture",
    "Alchemy",
    "Alcohol",
    "Algeria",
    "Algorithms",
    "Aliens",
    "Alternate History",
    "Alternative Medicine",
    "Amateur Sleuth",
    "Amazon",
    "American",
    "American Civil War",
    "American Fiction",
    "American History",
    "American Revolution",
    "American Revolutionary War",
    "American fiction",
    "American literature",
    "Americana",
    "Amish",
    "Anarchism",
    "Ancient",
    "Ancient History",
    "Angels",
    "Anglo Saxon",
    "Animal Fiction",
    "Animals",
    "Anime",
    "Anthologies",
    "Anthropology",
    "Anthropomorphic",
    "Anti Racist",
    "Antiques",
    "Apocalyptic",
    "Apple",
    "Archaeology",
    "Architecture",
    "Art",
    "Art Design",
    "Art History",
    "Art and Photography",
}
